providers = ["node"] # disable providers completely

[phases.setup]
    nixPkgs = [
        '...',
        "ffmpeg",
        "doppler",
    ] # Install the ffmpeg package from Nix and some other ones

[phases.build]
    cmds = ["bun upgrade", "bun --version"]
