providers = [] # disable providers completely

[phases.setup]
    nixPkgs = [
        '...',
        "ffmpeg",
        "doppler",
        "curl",
        "bash",
        "unzip",
    ] # Install the ffmpeg package from Nix and some other ones

[phases.build]
    cmds = [
        "echo first",
        "source /root/.bashrc",
        "curl -fsSL https://bun.sh/install | bash",
        "bun --version",
        "echo last",
    ]
